package com.yiding.saas.ydsaas.dao.domain;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_sequence
 *
 * @mbg.generated do_not_delete_during_merge 2019-03-18 16:56:05
 */
public class SysSequenceDO {
    /**
     * Database Column Remarks:
     *   主键id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_sequence.id
     *
     * @mbg.generated 2019-03-18 16:56:05
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   机房标识, -1: 不区分机房
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_sequence.idc_no
     *
     * @mbg.generated 2019-03-18 16:56:05
     */
    private Byte idcNo;

    /**
     * Database Column Remarks:
     *   分库路由 区间取决于mycat分库节点数，例目前为0-31
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_sequence.hash_route
     *
     * @mbg.generated 2019-03-18 16:56:05
     */
    private Integer hashRoute;

    /**
     * Database Column Remarks:
     *   业务名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_sequence.business_name
     *
     * @mbg.generated 2019-03-18 16:56:05
     */
    private String businessName;

    /**
     * Database Column Remarks:
     *   最小值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_sequence.min_value
     *
     * @mbg.generated 2019-03-18 16:56:05
     */
    private Long minValue;

    /**
     * Database Column Remarks:
     *   最大值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_sequence.max_value
     *
     * @mbg.generated 2019-03-18 16:56:05
     */
    private Long maxValue;

    /**
     * Database Column Remarks:
     *   步长值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_sequence.increase_step
     *
     * @mbg.generated 2019-03-18 16:56:05
     */
    private Integer increaseStep;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_sequence.locknum
     *
     * @mbg.generated 2019-03-18 16:56:05
     */
    private String locknum;

    /**
     * Database Column Remarks:
     *   是否开启循环，0-不开启；1-开启（此字段留以后序列服务化使用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_sequence.is_loop
     *
     * @mbg.generated 2019-03-18 16:56:05
     */
    private Byte isLoop;

    /**
     * Database Column Remarks:
     *   循环初始值大小
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_sequence.loop_init_value
     *
     * @mbg.generated 2019-03-18 16:56:05
     */
    private Long loopInitValue;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_sequence.create_time
     *
     * @mbg.generated 2019-03-18 16:56:05
     */
    private Long createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_sequence.update_time
     *
     * @mbg.generated 2019-03-18 16:56:05
     */
    private Long updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_sequence.id
     *
     * @return the value of sys_sequence.id
     *
     * @mbg.generated 2019-03-18 16:56:05
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_sequence.id
     *
     * @param id the value for sys_sequence.id
     *
     * @mbg.generated 2019-03-18 16:56:05
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_sequence.idc_no
     *
     * @return the value of sys_sequence.idc_no
     *
     * @mbg.generated 2019-03-18 16:56:05
     */
    public Byte getIdcNo() {
        return idcNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_sequence.idc_no
     *
     * @param idcNo the value for sys_sequence.idc_no
     *
     * @mbg.generated 2019-03-18 16:56:05
     */
    public void setIdcNo(Byte idcNo) {
        this.idcNo = idcNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_sequence.hash_route
     *
     * @return the value of sys_sequence.hash_route
     *
     * @mbg.generated 2019-03-18 16:56:05
     */
    public Integer getHashRoute() {
        return hashRoute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_sequence.hash_route
     *
     * @param hashRoute the value for sys_sequence.hash_route
     *
     * @mbg.generated 2019-03-18 16:56:05
     */
    public void setHashRoute(Integer hashRoute) {
        this.hashRoute = hashRoute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_sequence.business_name
     *
     * @return the value of sys_sequence.business_name
     *
     * @mbg.generated 2019-03-18 16:56:05
     */
    public String getBusinessName() {
        return businessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_sequence.business_name
     *
     * @param businessName the value for sys_sequence.business_name
     *
     * @mbg.generated 2019-03-18 16:56:05
     */
    public void setBusinessName(String businessName) {
        this.businessName = businessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_sequence.min_value
     *
     * @return the value of sys_sequence.min_value
     *
     * @mbg.generated 2019-03-18 16:56:05
     */
    public Long getMinValue() {
        return minValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_sequence.min_value
     *
     * @param minValue the value for sys_sequence.min_value
     *
     * @mbg.generated 2019-03-18 16:56:05
     */
    public void setMinValue(Long minValue) {
        this.minValue = minValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_sequence.max_value
     *
     * @return the value of sys_sequence.max_value
     *
     * @mbg.generated 2019-03-18 16:56:05
     */
    public Long getMaxValue() {
        return maxValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_sequence.max_value
     *
     * @param maxValue the value for sys_sequence.max_value
     *
     * @mbg.generated 2019-03-18 16:56:05
     */
    public void setMaxValue(Long maxValue) {
        this.maxValue = maxValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_sequence.increase_step
     *
     * @return the value of sys_sequence.increase_step
     *
     * @mbg.generated 2019-03-18 16:56:05
     */
    public Integer getIncreaseStep() {
        return increaseStep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_sequence.increase_step
     *
     * @param increaseStep the value for sys_sequence.increase_step
     *
     * @mbg.generated 2019-03-18 16:56:05
     */
    public void setIncreaseStep(Integer increaseStep) {
        this.increaseStep = increaseStep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_sequence.locknum
     *
     * @return the value of sys_sequence.locknum
     *
     * @mbg.generated 2019-03-18 16:56:05
     */
    public String getLocknum() {
        return locknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_sequence.locknum
     *
     * @param locknum the value for sys_sequence.locknum
     *
     * @mbg.generated 2019-03-18 16:56:05
     */
    public void setLocknum(String locknum) {
        this.locknum = locknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_sequence.is_loop
     *
     * @return the value of sys_sequence.is_loop
     *
     * @mbg.generated 2019-03-18 16:56:05
     */
    public Byte getIsLoop() {
        return isLoop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_sequence.is_loop
     *
     * @param isLoop the value for sys_sequence.is_loop
     *
     * @mbg.generated 2019-03-18 16:56:05
     */
    public void setIsLoop(Byte isLoop) {
        this.isLoop = isLoop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_sequence.loop_init_value
     *
     * @return the value of sys_sequence.loop_init_value
     *
     * @mbg.generated 2019-03-18 16:56:05
     */
    public Long getLoopInitValue() {
        return loopInitValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_sequence.loop_init_value
     *
     * @param loopInitValue the value for sys_sequence.loop_init_value
     *
     * @mbg.generated 2019-03-18 16:56:05
     */
    public void setLoopInitValue(Long loopInitValue) {
        this.loopInitValue = loopInitValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_sequence.create_time
     *
     * @return the value of sys_sequence.create_time
     *
     * @mbg.generated 2019-03-18 16:56:05
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_sequence.create_time
     *
     * @param createTime the value for sys_sequence.create_time
     *
     * @mbg.generated 2019-03-18 16:56:05
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_sequence.update_time
     *
     * @return the value of sys_sequence.update_time
     *
     * @mbg.generated 2019-03-18 16:56:05
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_sequence.update_time
     *
     * @param updateTime the value for sys_sequence.update_time
     *
     * @mbg.generated 2019-03-18 16:56:05
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sequence
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static SysSequenceDO.Builder builder() {
        return new SysSequenceDO.Builder();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_sequence
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table sys_sequence
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private SysSequenceDO obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sys_sequence
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder() {
            this.obj = new SysSequenceDO();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column sys_sequence.id
         *
         * @param id the value for sys_sequence.id
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder id(Integer id) {
            obj.setId(id);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column sys_sequence.idc_no
         *
         * @param idcNo the value for sys_sequence.idc_no
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder idcNo(Byte idcNo) {
            obj.setIdcNo(idcNo);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column sys_sequence.hash_route
         *
         * @param hashRoute the value for sys_sequence.hash_route
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder hashRoute(Integer hashRoute) {
            obj.setHashRoute(hashRoute);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column sys_sequence.business_name
         *
         * @param businessName the value for sys_sequence.business_name
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder businessName(String businessName) {
            obj.setBusinessName(businessName);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column sys_sequence.min_value
         *
         * @param minValue the value for sys_sequence.min_value
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder minValue(Long minValue) {
            obj.setMinValue(minValue);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column sys_sequence.max_value
         *
         * @param maxValue the value for sys_sequence.max_value
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder maxValue(Long maxValue) {
            obj.setMaxValue(maxValue);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column sys_sequence.increase_step
         *
         * @param increaseStep the value for sys_sequence.increase_step
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder increaseStep(Integer increaseStep) {
            obj.setIncreaseStep(increaseStep);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column sys_sequence.locknum
         *
         * @param locknum the value for sys_sequence.locknum
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder locknum(String locknum) {
            obj.setLocknum(locknum);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column sys_sequence.is_loop
         *
         * @param isLoop the value for sys_sequence.is_loop
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder isLoop(Byte isLoop) {
            obj.setIsLoop(isLoop);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column sys_sequence.loop_init_value
         *
         * @param loopInitValue the value for sys_sequence.loop_init_value
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder loopInitValue(Long loopInitValue) {
            obj.setLoopInitValue(loopInitValue);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column sys_sequence.create_time
         *
         * @param createTime the value for sys_sequence.create_time
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder createTime(Long createTime) {
            obj.setCreateTime(createTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column sys_sequence.update_time
         *
         * @param updateTime the value for sys_sequence.update_time
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder updateTime(Long updateTime) {
            obj.setUpdateTime(updateTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sys_sequence
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public SysSequenceDO build() {
            return this.obj;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table sys_sequence
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id"),
        idcNo("idc_no"),
        hashRoute("hash_route"),
        businessName("business_name"),
        minValue("min_value"),
        maxValue("max_value"),
        increaseStep("increase_step"),
        locknum("locknum"),
        isLoop("is_loop"),
        loopInitValue("loop_init_value"),
        createTime("create_time"),
        updateTime("update_time");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table sys_sequence
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sys_sequence
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sys_sequence
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sys_sequence
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column) {
            this.column = column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sys_sequence
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sys_sequence
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}