package com.yiding.saas.ydsaas.dao.domain;

import java.util.ArrayList;
import java.util.List;

public class SysSequenceDOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_sequence
     *
     * @mbg.generated 2019-03-18 16:56:05
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_sequence
     *
     * @mbg.generated 2019-03-18 16:56:05
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_sequence
     *
     * @mbg.generated 2019-03-18 16:56:05
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_sequence
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    protected Integer offset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_sequence
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    protected Integer rows;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sequence
     *
     * @mbg.generated 2019-03-18 16:56:05
     */
    public SysSequenceDOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sequence
     *
     * @mbg.generated 2019-03-18 16:56:05
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sequence
     *
     * @mbg.generated 2019-03-18 16:56:05
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sequence
     *
     * @mbg.generated 2019-03-18 16:56:05
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sequence
     *
     * @mbg.generated 2019-03-18 16:56:05
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sequence
     *
     * @mbg.generated 2019-03-18 16:56:05
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sequence
     *
     * @mbg.generated 2019-03-18 16:56:05
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sequence
     *
     * @mbg.generated 2019-03-18 16:56:05
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sequence
     *
     * @mbg.generated 2019-03-18 16:56:05
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sequence
     *
     * @mbg.generated 2019-03-18 16:56:05
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sequence
     *
     * @mbg.generated 2019-03-18 16:56:05
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        rows = null;
        offset = null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sequence
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sequence
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public Integer getOffset() {
        return this.offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sequence
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setRows(Integer rows) {
        this.rows = rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sequence
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public Integer getRows() {
        return this.rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sequence
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public SysSequenceDOExample limit(Integer rows) {
        this.rows = rows;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sequence
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public SysSequenceDOExample limit(Integer offset, Integer rows) {
        this.offset = offset;
        this.rows = rows;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sequence
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public SysSequenceDOExample page(Integer page, Integer pageSize) {
        this.offset = page * pageSize;
        this.rows = pageSize;
        return this;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_sequence
     *
     * @mbg.generated 2019-03-18 16:56:05
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdcNoIsNull() {
            addCriterion("idc_no is null");
            return (Criteria) this;
        }

        public Criteria andIdcNoIsNotNull() {
            addCriterion("idc_no is not null");
            return (Criteria) this;
        }

        public Criteria andIdcNoEqualTo(Byte value) {
            addCriterion("idc_no =", value, "idcNo");
            return (Criteria) this;
        }

        public Criteria andIdcNoNotEqualTo(Byte value) {
            addCriterion("idc_no <>", value, "idcNo");
            return (Criteria) this;
        }

        public Criteria andIdcNoGreaterThan(Byte value) {
            addCriterion("idc_no >", value, "idcNo");
            return (Criteria) this;
        }

        public Criteria andIdcNoGreaterThanOrEqualTo(Byte value) {
            addCriterion("idc_no >=", value, "idcNo");
            return (Criteria) this;
        }

        public Criteria andIdcNoLessThan(Byte value) {
            addCriterion("idc_no <", value, "idcNo");
            return (Criteria) this;
        }

        public Criteria andIdcNoLessThanOrEqualTo(Byte value) {
            addCriterion("idc_no <=", value, "idcNo");
            return (Criteria) this;
        }

        public Criteria andIdcNoIn(List<Byte> values) {
            addCriterion("idc_no in", values, "idcNo");
            return (Criteria) this;
        }

        public Criteria andIdcNoNotIn(List<Byte> values) {
            addCriterion("idc_no not in", values, "idcNo");
            return (Criteria) this;
        }

        public Criteria andIdcNoBetween(Byte value1, Byte value2) {
            addCriterion("idc_no between", value1, value2, "idcNo");
            return (Criteria) this;
        }

        public Criteria andIdcNoNotBetween(Byte value1, Byte value2) {
            addCriterion("idc_no not between", value1, value2, "idcNo");
            return (Criteria) this;
        }

        public Criteria andHashRouteIsNull() {
            addCriterion("hash_route is null");
            return (Criteria) this;
        }

        public Criteria andHashRouteIsNotNull() {
            addCriterion("hash_route is not null");
            return (Criteria) this;
        }

        public Criteria andHashRouteEqualTo(Integer value) {
            addCriterion("hash_route =", value, "hashRoute");
            return (Criteria) this;
        }

        public Criteria andHashRouteNotEqualTo(Integer value) {
            addCriterion("hash_route <>", value, "hashRoute");
            return (Criteria) this;
        }

        public Criteria andHashRouteGreaterThan(Integer value) {
            addCriterion("hash_route >", value, "hashRoute");
            return (Criteria) this;
        }

        public Criteria andHashRouteGreaterThanOrEqualTo(Integer value) {
            addCriterion("hash_route >=", value, "hashRoute");
            return (Criteria) this;
        }

        public Criteria andHashRouteLessThan(Integer value) {
            addCriterion("hash_route <", value, "hashRoute");
            return (Criteria) this;
        }

        public Criteria andHashRouteLessThanOrEqualTo(Integer value) {
            addCriterion("hash_route <=", value, "hashRoute");
            return (Criteria) this;
        }

        public Criteria andHashRouteIn(List<Integer> values) {
            addCriterion("hash_route in", values, "hashRoute");
            return (Criteria) this;
        }

        public Criteria andHashRouteNotIn(List<Integer> values) {
            addCriterion("hash_route not in", values, "hashRoute");
            return (Criteria) this;
        }

        public Criteria andHashRouteBetween(Integer value1, Integer value2) {
            addCriterion("hash_route between", value1, value2, "hashRoute");
            return (Criteria) this;
        }

        public Criteria andHashRouteNotBetween(Integer value1, Integer value2) {
            addCriterion("hash_route not between", value1, value2, "hashRoute");
            return (Criteria) this;
        }

        public Criteria andBusinessNameIsNull() {
            addCriterion("business_name is null");
            return (Criteria) this;
        }

        public Criteria andBusinessNameIsNotNull() {
            addCriterion("business_name is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessNameEqualTo(String value) {
            addCriterion("business_name =", value, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameNotEqualTo(String value) {
            addCriterion("business_name <>", value, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameGreaterThan(String value) {
            addCriterion("business_name >", value, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameGreaterThanOrEqualTo(String value) {
            addCriterion("business_name >=", value, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameLessThan(String value) {
            addCriterion("business_name <", value, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameLessThanOrEqualTo(String value) {
            addCriterion("business_name <=", value, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameLike(String value) {
            addCriterion("business_name like", value, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameNotLike(String value) {
            addCriterion("business_name not like", value, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameIn(List<String> values) {
            addCriterion("business_name in", values, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameNotIn(List<String> values) {
            addCriterion("business_name not in", values, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameBetween(String value1, String value2) {
            addCriterion("business_name between", value1, value2, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameNotBetween(String value1, String value2) {
            addCriterion("business_name not between", value1, value2, "businessName");
            return (Criteria) this;
        }

        public Criteria andMinValueIsNull() {
            addCriterion("min_value is null");
            return (Criteria) this;
        }

        public Criteria andMinValueIsNotNull() {
            addCriterion("min_value is not null");
            return (Criteria) this;
        }

        public Criteria andMinValueEqualTo(Long value) {
            addCriterion("min_value =", value, "minValue");
            return (Criteria) this;
        }

        public Criteria andMinValueNotEqualTo(Long value) {
            addCriterion("min_value <>", value, "minValue");
            return (Criteria) this;
        }

        public Criteria andMinValueGreaterThan(Long value) {
            addCriterion("min_value >", value, "minValue");
            return (Criteria) this;
        }

        public Criteria andMinValueGreaterThanOrEqualTo(Long value) {
            addCriterion("min_value >=", value, "minValue");
            return (Criteria) this;
        }

        public Criteria andMinValueLessThan(Long value) {
            addCriterion("min_value <", value, "minValue");
            return (Criteria) this;
        }

        public Criteria andMinValueLessThanOrEqualTo(Long value) {
            addCriterion("min_value <=", value, "minValue");
            return (Criteria) this;
        }

        public Criteria andMinValueIn(List<Long> values) {
            addCriterion("min_value in", values, "minValue");
            return (Criteria) this;
        }

        public Criteria andMinValueNotIn(List<Long> values) {
            addCriterion("min_value not in", values, "minValue");
            return (Criteria) this;
        }

        public Criteria andMinValueBetween(Long value1, Long value2) {
            addCriterion("min_value between", value1, value2, "minValue");
            return (Criteria) this;
        }

        public Criteria andMinValueNotBetween(Long value1, Long value2) {
            addCriterion("min_value not between", value1, value2, "minValue");
            return (Criteria) this;
        }

        public Criteria andMaxValueIsNull() {
            addCriterion("max_value is null");
            return (Criteria) this;
        }

        public Criteria andMaxValueIsNotNull() {
            addCriterion("max_value is not null");
            return (Criteria) this;
        }

        public Criteria andMaxValueEqualTo(Long value) {
            addCriterion("max_value =", value, "maxValue");
            return (Criteria) this;
        }

        public Criteria andMaxValueNotEqualTo(Long value) {
            addCriterion("max_value <>", value, "maxValue");
            return (Criteria) this;
        }

        public Criteria andMaxValueGreaterThan(Long value) {
            addCriterion("max_value >", value, "maxValue");
            return (Criteria) this;
        }

        public Criteria andMaxValueGreaterThanOrEqualTo(Long value) {
            addCriterion("max_value >=", value, "maxValue");
            return (Criteria) this;
        }

        public Criteria andMaxValueLessThan(Long value) {
            addCriterion("max_value <", value, "maxValue");
            return (Criteria) this;
        }

        public Criteria andMaxValueLessThanOrEqualTo(Long value) {
            addCriterion("max_value <=", value, "maxValue");
            return (Criteria) this;
        }

        public Criteria andMaxValueIn(List<Long> values) {
            addCriterion("max_value in", values, "maxValue");
            return (Criteria) this;
        }

        public Criteria andMaxValueNotIn(List<Long> values) {
            addCriterion("max_value not in", values, "maxValue");
            return (Criteria) this;
        }

        public Criteria andMaxValueBetween(Long value1, Long value2) {
            addCriterion("max_value between", value1, value2, "maxValue");
            return (Criteria) this;
        }

        public Criteria andMaxValueNotBetween(Long value1, Long value2) {
            addCriterion("max_value not between", value1, value2, "maxValue");
            return (Criteria) this;
        }

        public Criteria andIncreaseStepIsNull() {
            addCriterion("increase_step is null");
            return (Criteria) this;
        }

        public Criteria andIncreaseStepIsNotNull() {
            addCriterion("increase_step is not null");
            return (Criteria) this;
        }

        public Criteria andIncreaseStepEqualTo(Integer value) {
            addCriterion("increase_step =", value, "increaseStep");
            return (Criteria) this;
        }

        public Criteria andIncreaseStepNotEqualTo(Integer value) {
            addCriterion("increase_step <>", value, "increaseStep");
            return (Criteria) this;
        }

        public Criteria andIncreaseStepGreaterThan(Integer value) {
            addCriterion("increase_step >", value, "increaseStep");
            return (Criteria) this;
        }

        public Criteria andIncreaseStepGreaterThanOrEqualTo(Integer value) {
            addCriterion("increase_step >=", value, "increaseStep");
            return (Criteria) this;
        }

        public Criteria andIncreaseStepLessThan(Integer value) {
            addCriterion("increase_step <", value, "increaseStep");
            return (Criteria) this;
        }

        public Criteria andIncreaseStepLessThanOrEqualTo(Integer value) {
            addCriterion("increase_step <=", value, "increaseStep");
            return (Criteria) this;
        }

        public Criteria andIncreaseStepIn(List<Integer> values) {
            addCriterion("increase_step in", values, "increaseStep");
            return (Criteria) this;
        }

        public Criteria andIncreaseStepNotIn(List<Integer> values) {
            addCriterion("increase_step not in", values, "increaseStep");
            return (Criteria) this;
        }

        public Criteria andIncreaseStepBetween(Integer value1, Integer value2) {
            addCriterion("increase_step between", value1, value2, "increaseStep");
            return (Criteria) this;
        }

        public Criteria andIncreaseStepNotBetween(Integer value1, Integer value2) {
            addCriterion("increase_step not between", value1, value2, "increaseStep");
            return (Criteria) this;
        }

        public Criteria andLocknumIsNull() {
            addCriterion("locknum is null");
            return (Criteria) this;
        }

        public Criteria andLocknumIsNotNull() {
            addCriterion("locknum is not null");
            return (Criteria) this;
        }

        public Criteria andLocknumEqualTo(String value) {
            addCriterion("locknum =", value, "locknum");
            return (Criteria) this;
        }

        public Criteria andLocknumNotEqualTo(String value) {
            addCriterion("locknum <>", value, "locknum");
            return (Criteria) this;
        }

        public Criteria andLocknumGreaterThan(String value) {
            addCriterion("locknum >", value, "locknum");
            return (Criteria) this;
        }

        public Criteria andLocknumGreaterThanOrEqualTo(String value) {
            addCriterion("locknum >=", value, "locknum");
            return (Criteria) this;
        }

        public Criteria andLocknumLessThan(String value) {
            addCriterion("locknum <", value, "locknum");
            return (Criteria) this;
        }

        public Criteria andLocknumLessThanOrEqualTo(String value) {
            addCriterion("locknum <=", value, "locknum");
            return (Criteria) this;
        }

        public Criteria andLocknumLike(String value) {
            addCriterion("locknum like", value, "locknum");
            return (Criteria) this;
        }

        public Criteria andLocknumNotLike(String value) {
            addCriterion("locknum not like", value, "locknum");
            return (Criteria) this;
        }

        public Criteria andLocknumIn(List<String> values) {
            addCriterion("locknum in", values, "locknum");
            return (Criteria) this;
        }

        public Criteria andLocknumNotIn(List<String> values) {
            addCriterion("locknum not in", values, "locknum");
            return (Criteria) this;
        }

        public Criteria andLocknumBetween(String value1, String value2) {
            addCriterion("locknum between", value1, value2, "locknum");
            return (Criteria) this;
        }

        public Criteria andLocknumNotBetween(String value1, String value2) {
            addCriterion("locknum not between", value1, value2, "locknum");
            return (Criteria) this;
        }

        public Criteria andIsLoopIsNull() {
            addCriterion("is_loop is null");
            return (Criteria) this;
        }

        public Criteria andIsLoopIsNotNull() {
            addCriterion("is_loop is not null");
            return (Criteria) this;
        }

        public Criteria andIsLoopEqualTo(Byte value) {
            addCriterion("is_loop =", value, "isLoop");
            return (Criteria) this;
        }

        public Criteria andIsLoopNotEqualTo(Byte value) {
            addCriterion("is_loop <>", value, "isLoop");
            return (Criteria) this;
        }

        public Criteria andIsLoopGreaterThan(Byte value) {
            addCriterion("is_loop >", value, "isLoop");
            return (Criteria) this;
        }

        public Criteria andIsLoopGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_loop >=", value, "isLoop");
            return (Criteria) this;
        }

        public Criteria andIsLoopLessThan(Byte value) {
            addCriterion("is_loop <", value, "isLoop");
            return (Criteria) this;
        }

        public Criteria andIsLoopLessThanOrEqualTo(Byte value) {
            addCriterion("is_loop <=", value, "isLoop");
            return (Criteria) this;
        }

        public Criteria andIsLoopIn(List<Byte> values) {
            addCriterion("is_loop in", values, "isLoop");
            return (Criteria) this;
        }

        public Criteria andIsLoopNotIn(List<Byte> values) {
            addCriterion("is_loop not in", values, "isLoop");
            return (Criteria) this;
        }

        public Criteria andIsLoopBetween(Byte value1, Byte value2) {
            addCriterion("is_loop between", value1, value2, "isLoop");
            return (Criteria) this;
        }

        public Criteria andIsLoopNotBetween(Byte value1, Byte value2) {
            addCriterion("is_loop not between", value1, value2, "isLoop");
            return (Criteria) this;
        }

        public Criteria andLoopInitValueIsNull() {
            addCriterion("loop_init_value is null");
            return (Criteria) this;
        }

        public Criteria andLoopInitValueIsNotNull() {
            addCriterion("loop_init_value is not null");
            return (Criteria) this;
        }

        public Criteria andLoopInitValueEqualTo(Long value) {
            addCriterion("loop_init_value =", value, "loopInitValue");
            return (Criteria) this;
        }

        public Criteria andLoopInitValueNotEqualTo(Long value) {
            addCriterion("loop_init_value <>", value, "loopInitValue");
            return (Criteria) this;
        }

        public Criteria andLoopInitValueGreaterThan(Long value) {
            addCriterion("loop_init_value >", value, "loopInitValue");
            return (Criteria) this;
        }

        public Criteria andLoopInitValueGreaterThanOrEqualTo(Long value) {
            addCriterion("loop_init_value >=", value, "loopInitValue");
            return (Criteria) this;
        }

        public Criteria andLoopInitValueLessThan(Long value) {
            addCriterion("loop_init_value <", value, "loopInitValue");
            return (Criteria) this;
        }

        public Criteria andLoopInitValueLessThanOrEqualTo(Long value) {
            addCriterion("loop_init_value <=", value, "loopInitValue");
            return (Criteria) this;
        }

        public Criteria andLoopInitValueIn(List<Long> values) {
            addCriterion("loop_init_value in", values, "loopInitValue");
            return (Criteria) this;
        }

        public Criteria andLoopInitValueNotIn(List<Long> values) {
            addCriterion("loop_init_value not in", values, "loopInitValue");
            return (Criteria) this;
        }

        public Criteria andLoopInitValueBetween(Long value1, Long value2) {
            addCriterion("loop_init_value between", value1, value2, "loopInitValue");
            return (Criteria) this;
        }

        public Criteria andLoopInitValueNotBetween(Long value1, Long value2) {
            addCriterion("loop_init_value not between", value1, value2, "loopInitValue");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Long value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Long value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Long value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Long value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Long value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Long> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Long> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Long value1, Long value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Long value1, Long value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Long value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Long value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Long value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Long value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Long value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Long> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Long> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Long value1, Long value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Long value1, Long value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_sequence
     *
     * @mbg.generated do_not_delete_during_merge 2019-03-18 16:56:05
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_sequence
     *
     * @mbg.generated 2019-03-18 16:56:05
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}